'use client';

import { useState } from 'react';
import { ChartRecommendation } from '@/lib/types';
import { TrendingUp, BarChart3, LineChart, Circle, PieChart, Activity, BarChart2, TreePine, Share2, Square, ChevronDown, ChevronUp } from 'lucide-react';

interface RecommendationCardProps {
  recommendation: ChartRecommendation;
  onSelect: () => void;
  onAddToCanvas?: () => void;
  isSelected?: boolean;
}

const chartIcons = {
  line: LineChart,
  bar: BarChart3,
  scatter: Circle,
  pie: PieChart,
  histogram: BarChart2,
  box_plot: Square,
  heatmap: Activity,
  area: Activity,
  treemap: TreePine,
  sankey: Share2
};

const chartColors = {
  line: 'text-blue-500',
  bar: 'text-green-500',
  scatter: 'text-purple-500',
  pie: 'text-orange-500',
  histogram: 'text-indigo-500',
  box_plot: 'text-cyan-500',
  heatmap: 'text-red-500',
  area: 'text-pink-500',
  treemap: 'text-emerald-500',
  sankey: 'text-violet-500'
};

const MAX_DESCRIPTION_LENGTH = 120;
const MAX_JUSTIFICATION_LENGTH = 200;

export default function RecommendationCard({
  recommendation,
  onSelect,
  onAddToCanvas,
  isSelected = false
}: RecommendationCardProps) {
  const [isDescriptionExpanded, setIsDescriptionExpanded] = useState(false);
  const [isJustificationExpanded, setIsJustificationExpanded] = useState(false);

  const Icon = chartIcons[recommendation.chartType] || TrendingUp;
  const iconColor = chartColors[recommendation.chartType] || 'text-gray-500';

  // Generate intelligent title based on chart config
  const getChartTitle = () => {
    // First try to use the title from the config (which should be generated by the agent)
    if (recommendation.config?.title && recommendation.config.title !== 'Untitled Chart') {
      return recommendation.config.title;
    }

    // If no title, generate one based on the chart type and data mapping
    const { config, chartType } = recommendation;

    if (config.xAxis && config.yAxis) {
      const chartTypeLabel = chartType ? (chartType.charAt(0).toUpperCase() + chartType.slice(1)) : 'Chart';
      return `${config.yAxis} vs ${config.xAxis}`;
    } else if (config.category && config.value) {
      return `${config.value} by ${config.category}`;
    } else if (config.xAxis) {
      return `Distribution of ${config.xAxis}`;
    }

    // Fallback to a more descriptive default
    return chartType ? `${chartType.charAt(0).toUpperCase() + chartType.slice(1)} Visualization` : 'Chart Visualization';
  };

  // Generate description based on chart type and purpose
  const getChartDescription = () => {
    const { config, chartType } = recommendation;

    switch (chartType) {
      case 'line':
        return `Track trends and changes in ${config.yAxis || 'values'} over ${config.xAxis || 'time'}. Ideal for temporal data analysis.`;
      case 'bar':
        return `Compare ${config.yAxis || 'values'} across different ${config.xAxis || 'categories'}. Perfect for categorical comparisons.`;
      case 'scatter':
        return `Explore the relationship between ${config.xAxis} and ${config.yAxis}. Great for identifying correlations and patterns.`;
      case 'pie':
        return `Show proportional breakdown of ${config.value || 'values'} by ${config.category || 'category'}. Best for part-to-whole relationships.`;
      case 'histogram':
        return `Display the distribution of ${config.xAxis || 'values'}. Useful for understanding data frequency and patterns.`;
      case 'heatmap':
        return `Visualize data density and patterns through color intensity. Excellent for matrix data and correlation analysis.`;
      case 'area':
        return `Show cumulative values and trends over ${config.xAxis || 'time'}. Good for stacked data visualization.`;
      default:
        return `Visualize your data using ${chartType} format. Tailored for your specific dataset characteristics.`;
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 80) return 'text-green-600 bg-green-50 border-green-200';
    if (confidence >= 65) return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    return 'text-red-600 bg-red-50 border-red-200';
  };

  const getDataMappingText = () => {
    const { config } = recommendation;
    const parts = [];

    if (config.xAxis) parts.push(`X: ${config.xAxis}`);
    if (config.yAxis) parts.push(`Y: ${config.yAxis}`);
    if (config.category) parts.push(`Category: ${config.category}`);
    if (config.value) parts.push(`Value: ${config.value}`);

    return parts.join(' • ');
  };

  const truncateText = (text: string, maxLength: number) => {
    if (text.length <= maxLength) return text;
    return text.substring(0, maxLength).trim() + '…';
  };

  const description = getChartDescription();
  const shouldShowDescriptionToggle = description.length > MAX_DESCRIPTION_LENGTH;
  const displayDescription = isDescriptionExpanded ? description : truncateText(description, MAX_DESCRIPTION_LENGTH);

  const shouldShowJustificationToggle = recommendation.justification.length > MAX_JUSTIFICATION_LENGTH;
  const displayJustification = isJustificationExpanded ? recommendation.justification : truncateText(recommendation.justification, MAX_JUSTIFICATION_LENGTH);

  return (
    <div
      className={`
        bg-white rounded-lg shadow-sm border-2 p-4 cursor-pointer transition-all duration-200
        ${isSelected
          ? 'border-blue-500 bg-blue-50'
          : 'border-gray-200 hover:border-gray-300 hover:shadow-md'
        }
      `}
      onClick={onSelect}
    >
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Icon className={`h-5 w-5 ${iconColor}`} />
          <h3 className="font-semibold text-gray-900">
            {getChartTitle()}
          </h3>
        </div>
        <span
          className={`text-xs font-medium px-2 py-1 rounded-full border ${getConfidenceColor(recommendation.confidence)}`}
        >
          {Math.round(recommendation.confidence)}% confidence
        </span>
      </div>

      <div className="mb-3">
        <div className="text-sm text-gray-600 mb-3 leading-relaxed">
          {displayDescription}
          {shouldShowDescriptionToggle && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                setIsDescriptionExpanded(!isDescriptionExpanded);
              }}
              className="text-blue-600 hover:text-blue-800 text-xs font-medium ml-1 focus:outline-none"
            >
              {isDescriptionExpanded ? (
                <span className="flex items-center gap-1">
                  <ChevronUp className="h-3 w-3" /> Show less
                </span>
              ) : (
                <span className="flex items-center gap-1">
                  <ChevronDown className="h-3 w-3" /> Read more
                </span>
              )}
            </button>
          )}
        </div>

        <div className="flex items-center gap-1 mb-2">
          <span className="text-xs font-medium text-gray-500 uppercase tracking-wide">Why this chart?</span>
        </div>
        <div className="text-sm text-gray-700 leading-relaxed bg-gray-50 p-3 rounded-md border-l-4 border-blue-200">
          {displayJustification}
          {shouldShowJustificationToggle && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                setIsJustificationExpanded(!isJustificationExpanded);
              }}
              className="text-blue-600 hover:text-blue-800 text-xs font-medium ml-1 mt-2 focus:outline-none block"
            >
              {isJustificationExpanded ? (
                <span className="flex items-center gap-1">
                  <ChevronUp className="h-3 w-3" /> Show less
                </span>
              ) : (
                <span className="flex items-center gap-1">
                  <ChevronDown className="h-3 w-3" /> Read more
                </span>
              )}
            </button>
          )}
        </div>
      </div>

      {getDataMappingText() && (
        <div className="mb-3">
          <p className="text-xs text-gray-500 mb-1">Data Mapping:</p>
          <p className="text-xs text-gray-700 font-mono bg-gray-50 px-2 py-1 rounded">
            {getDataMappingText()}
          </p>
        </div>
      )}

      <div className="flex gap-2">
        <button
          className={`
            flex-1 py-2 px-4 rounded-md font-medium text-sm transition-colors
            ${isSelected
              ? 'bg-blue-600 text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }
          `}
        >
          {isSelected ? 'Selected' : 'Select Chart'}
        </button>
        <button
          onClick={(e) => {
            e.stopPropagation();
            onAddToCanvas?.();
          }}
          className="px-3 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors text-sm font-medium"
          title="Add to Canvas"
        >
          + Canvas
        </button>
      </div>
    </div>
  );
}